layout_spectrum: 0.4808769
color:
  saturation: 0.1934759
  lightness: 0.7751865
  brandStrength: 1
  brandColors:
    - '#164845'
    - '#000202'
    - '#97C8D7'
    - '#9F8758'
    - '#FDA58A'
  rhythmicContrast: 0.6112903
typography_spectrum: 0.04291045
name: 'TR∆DED∆RT '
