name: 'TR∆DED∆RT '
favicon: null
layout_spectrum: 0.8398
typography_spectrum: 0.07248
title: SHARING IS CARING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2321'
    - '#dc9749'
    - '#843719'
    - '#43b3c7'
    - '#b36b31'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
