title: SHARING IS CARING
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0.0625
  rhythmicContrast: 0.75
  brandColors:
    - '#2b2321'
    - '#dc9749'
    - '#843719'
    - '#43b3c7'
    - '#b36b31'
  lightness: 0.8125
cta:
  bucket: null
  version: null
  domain: null
name: 'TR∆DED∆RT '
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.07679911
layout_spectrum: 0.4656284
