title: SHARING IS CARING
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 1
  rhythmicContrast: 0.75
  brandColors:
    - '#2B2321'
    - '#7F3317'
    - '#D6934A'
    - '#AD6430'
    - '#56756E'
  lightness: 0.8125
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: 'TR∆DED∆RT '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.07679911
layout_spectrum: 1
